# CMake generated Testfile for 
# Source directory: C:/dev/Powershell/nodus
# Build directory: C:/dev/Powershell/nodus/build_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(thread_manager_test "C:/dev/Powershell/nodus/build_test/Debug/test_thread_manager.exe")
  set_tests_properties(thread_manager_test PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/Powershell/nodus/CMakeLists.txt;46;add_test;C:/dev/Powershell/nodus/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(thread_manager_test "C:/dev/Powershell/nodus/build_test/Release/test_thread_manager.exe")
  set_tests_properties(thread_manager_test PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/Powershell/nodus/CMakeLists.txt;46;add_test;C:/dev/Powershell/nodus/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(thread_manager_test "C:/dev/Powershell/nodus/build_test/MinSizeRel/test_thread_manager.exe")
  set_tests_properties(thread_manager_test PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/Powershell/nodus/CMakeLists.txt;46;add_test;C:/dev/Powershell/nodus/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(thread_manager_test "C:/dev/Powershell/nodus/build_test/RelWithDebInfo/test_thread_manager.exe")
  set_tests_properties(thread_manager_test PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/Powershell/nodus/CMakeLists.txt;46;add_test;C:/dev/Powershell/nodus/CMakeLists.txt;0;")
else()
  add_test(thread_manager_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(tool_dll_test "C:/Users/alber/AppData/Local/Programs/Python/Python310/python.exe" "C:/dev/Powershell/nodus/tests/tool_dll_test.py")
  set_tests_properties(tool_dll_test PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/Powershell/nodus/CMakeLists.txt;49;add_test;C:/dev/Powershell/nodus/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(tool_dll_test "C:/Users/alber/AppData/Local/Programs/Python/Python310/python.exe" "C:/dev/Powershell/nodus/tests/tool_dll_test.py")
  set_tests_properties(tool_dll_test PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/Powershell/nodus/CMakeLists.txt;49;add_test;C:/dev/Powershell/nodus/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(tool_dll_test "C:/Users/alber/AppData/Local/Programs/Python/Python310/python.exe" "C:/dev/Powershell/nodus/tests/tool_dll_test.py")
  set_tests_properties(tool_dll_test PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/Powershell/nodus/CMakeLists.txt;49;add_test;C:/dev/Powershell/nodus/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(tool_dll_test "C:/Users/alber/AppData/Local/Programs/Python/Python310/python.exe" "C:/dev/Powershell/nodus/tests/tool_dll_test.py")
  set_tests_properties(tool_dll_test PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/Powershell/nodus/CMakeLists.txt;49;add_test;C:/dev/Powershell/nodus/CMakeLists.txt;0;")
else()
  add_test(tool_dll_test NOT_AVAILABLE)
endif()
