cmake_minimum_required(VERSION 3.15)

if(NOT DEFINED DEV_BUNDLE_LIBTORCH)
  message(FATAL_ERROR "persist_torch.cmake requires DEV_BUNDLE_LIBTORCH to know where to write the bundle.")
endif()

set(_DEST_BIN "${DEV_BUNDLE_LIBTORCH}/bin")
set(_DEST_LIB "${DEV_BUNDLE_LIBTORCH}/lib")
set(_DEST_SHARE "${DEV_BUNDLE_LIBTORCH}/share/cmake/Torch")
set(_DEST_INCLUDE "${DEV_BUNDLE_LIBTORCH}/include")

file(MAKE_DIRECTORY "${_DEST_BIN}" "${_DEST_LIB}" "${_DEST_SHARE}" "${_DEST_INCLUDE}")

function(_copy_if_exists _source _dest)
  if(EXISTS "${_source}")
    file(COPY "${_source}" DESTINATION "${_dest}")
  else()
    message(WARNING "Persisting Torch: source ${_source} does not exist; skipping copy into ${_dest}")
  endif()
endfunction()

if(DEFINED TORCH_CONFIG_SOURCE)
  _copy_if_exists("${TORCH_CONFIG_SOURCE}" "${_DEST_SHARE}")
else()
  message(WARNING "persist_torch: TORCH_CONFIG_SOURCE not defined")
endif()

if(DEFINED TORCH_CONFIG_VERSION_SOURCE)
  _copy_if_exists("${TORCH_CONFIG_VERSION_SOURCE}" "${_DEST_SHARE}")
else()
  message(WARNING "persist_torch: TORCH_CONFIG_VERSION_SOURCE not defined")
endif()

if(DEFINED TORCH_LIB_SRC AND EXISTS "${TORCH_LIB_SRC}")
  file(GLOB _torch_lib_files "${TORCH_LIB_SRC}/*.lib")
  foreach(_lib IN LISTS _torch_lib_files)
    file(COPY "${_lib}" DESTINATION "${_DEST_LIB}")
  endforeach()
else()
  message(WARNING "Torch lib output directory ${TORCH_LIB_SRC} missing; no libs persisted.")
endif()

if(DEFINED TORCH_DLL_SRC AND EXISTS "${TORCH_DLL_SRC}")
  file(GLOB _torch_dll_files "${TORCH_DLL_SRC}/*.dll")
  foreach(_dll IN LISTS _torch_dll_files)
    file(COPY "${_dll}" DESTINATION "${_DEST_BIN}")
  endforeach()
else()
  message(WARNING "Torch DLL output directory ${TORCH_DLL_SRC} missing; no DLLs persisted.")
endif()

if(DEFINED DEV_BUNDLE_BIN AND EXISTS "${_DEST_BIN}")
  file(COPY "${_DEST_BIN}/" DESTINATION "${DEV_BUNDLE_BIN}")
endif()

if(DEFINED TORCH_INCLUDE_DIRS)
  foreach(_inc IN LISTS TORCH_INCLUDE_DIRS)
    if(EXISTS "${_inc}")
      file(COPY "${_inc}/" DESTINATION "${_DEST_INCLUDE}")
    else()
      message(WARNING "Torch include directory ${_inc} missing; skipping persistence.")
    endif()
  endforeach()
endif()

message(STATUS "Persisted Torch binaries -> ${DEV_BUNDLE_LIBTORCH}")
