"""GENERATED FILE -- DO NOT EDIT.

Source:    ops/canonical_ops.json
Generator: ops/generate_canonical_ops.py
Rationale: research/15_the_missing_function_table.md
"""

from __future__ import annotations

from enum import IntEnum
from typing import NamedTuple


class CanonicalOp(IntEnum):
    """Append-only operation IDs shared by all lowering surfaces."""
    ADD = 0  # CT_OP_ADD
    SUB = 1  # CT_OP_SUB
    MUL = 2  # CT_OP_MUL
    TRUEDIV = 3  # CT_OP_DIV
    POW = 4  # CT_OP_POW
    MOD = 5  # CT_OP_MOD
    FLOORDIV = 6  # CT_OP_FLOORDIV
    SQRT = 7  # CT_OP_SQRT
    EXP = 8  # CT_OP_EXP
    LOG = 9  # CT_OP_LOG
    NEG = 10  # CT_OP_NEG
    ABS = 11  # CT_OP_ABS
    ROUND = 12  # CT_OP_ROUND
    TRUNC = 13  # CT_OP_TRUNC
    FLOOR = 14  # CT_OP_FLOOR
    CEIL = 15  # CT_OP_CEIL
    ISFINITE = 16  # CT_OP_ISFINITE
    ISNAN = 17  # CT_OP_ISNAN
    ISINF = 18  # CT_OP_ISINF
    LOGICAL_NOT = 19  # CT_OP_LOGICAL_NOT
    LESS = 20  # CT_OP_LT
    LESS_EQUAL = 21  # CT_OP_LE
    GREATER = 22  # CT_OP_GT
    GREATER_EQUAL = 23  # CT_OP_GE
    EQUAL = 24  # CT_OP_EQ
    NOT_EQUAL = 25  # CT_OP_NE
    MAXIMUM = 26  # CT_OP_MAXIMUM
    MINIMUM = 27  # CT_OP_MINIMUM
    SIGN = 28  # CT_OP_SIGN
    INVERT = 29  # CT_OP_INVERT
    SIN = 30  # CT_OP_SIN
    COS = 31  # CT_OP_COS
    TAN = 32  # CT_OP_TAN
    ASIN = 33  # CT_OP_ASIN
    ACOS = 34  # CT_OP_ACOS
    ATAN = 35  # CT_OP_ATAN
    SINH = 36  # CT_OP_SINH
    COSH = 37  # CT_OP_COSH
    TANH = 38  # CT_OP_TANH
    ASINH = 39  # CT_OP_ASINH
    ACOSH = 40  # CT_OP_ACOSH
    ATANH = 41  # CT_OP_ATANH
    BITAND = 42  # CT_OP_BITAND
    BITOR = 43  # CT_OP_BITOR
    BITXOR = 44  # CT_OP_BITXOR
    SHL = 45  # CT_OP_SHL
    SHR = 46  # CT_OP_SHR
    LOGICAL_AND = 47  # CT_OP_LOGICAL_AND
    LOGICAL_OR = 48  # CT_OP_LOGICAL_OR
    INT_TRUNC = 49
    ZEXT = 50
    SEXT = 51
    FPTOSI = 52
    FPTOUI = 53
    SITOFP = 54
    UITOFP = 55
    MATMUL = 56
    SUM = 57
    MEAN = 58
    TOPK = 59
    LOG_SOFTMAX = 60
    PAD = 61
    STACK = 62
    CAT = 63
    GATHER = 64
    ARANGE = 65
    BR = 66
    CONDBR = 67
    INDIRECTBR = 68
    RET = 69
    TRAP = 70
    PHI = 71
    SELECT = 72
    DEPLOY = 73
    JOIN = 74
    ALLOCA = 75
    STORE = 76
    GETELEMENTPTR = 77
    GETATTR = 78
    INDEXED = 79
    INDEXEDSTORE = 80
    FILL = 81
    STRIDED_STORE_FILL = 82
    STRIDED_MEMORY_COPY = 83
    DEEPCOPY = 84
    CONST = 85
    STATIC_REF = 86
    SETATTR = 87
    CLASS_DEFINE = 88
    FIELD_DEFINE = 89
    METHOD_DEFINE = 90
    FUNCTION_DEFINE = 91
    SIGMOID = 92  # CT_OP_SIGMOID


class OpDesc(NamedTuple):
    name: str
    canonical_id: int
    op_class: str
    ct_op: str | None
    ct_value: int | None
    arity: int
    returns: str
    lowerable: bool
    reflectable: bool
    kernel_op: str | None
    handler: str | None
    sympy: tuple[str, ...]
    c_fn: str | None
    tier1_class: str | None
    notes: str | None


OPS: tuple[OpDesc, ...] = (
    OpDesc(
        canonical_id=0,
        name='add',
        op_class='binary',
        ct_op='CT_OP_ADD',
        ct_value=0,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='BINARY',
        handler='Add',
        sympy=('add',),
        c_fn=None,
        tier1_class=None,
        notes='Commutative, so the reverse flag is a no-op.',
    ),
    OpDesc(
        canonical_id=1,
        name='sub',
        op_class='binary',
        ct_op='CT_OP_SUB',
        ct_value=1,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Sub',
        sympy=('sub',),
        c_fn=None,
        tier1_class=None,
        notes="numpy/torch _apply_operator__ return 'a - b' for BOTH 'sub' and 'rsub'; the C backend's explicit reverse flag is correct where those two are not.",
    ),
    OpDesc(
        canonical_id=2,
        name='mul',
        op_class='binary',
        ct_op='CT_OP_MUL',
        ct_value=2,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='BINARY',
        handler='Mul',
        sympy=('mul',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=3,
        name='truediv',
        op_class='binary',
        ct_op='CT_OP_DIV',
        ct_value=3,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Div',
        sympy=('div',),
        c_fn=None,
        tier1_class=None,
        notes='numpy guards via _safe_divide; C does not guard division by zero.',
    ),
    OpDesc(
        canonical_id=4,
        name='pow',
        op_class='binary',
        ct_op='CT_OP_POW',
        ct_value=4,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Pow',
        sympy=('pow',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=5,
        name='mod',
        op_class='binary',
        ct_op='CT_OP_MOD',
        ct_value=5,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Mod',
        sympy=('mod',),
        c_fn=None,
        tier1_class=None,
        notes='C now computes a - floor(a/b)*b (floored, numpy/torch-compatible) rather than fmod. An emitter must not lower this to GLSL mod() for signed operands without checking.',
    ),
    OpDesc(
        canonical_id=6,
        name='floordiv',
        op_class='binary',
        ct_op='CT_OP_FLOORDIV',
        ct_value=6,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler=None,
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes="turing's Handler has no floor-division member; it would coarsen to Div + floor.",
    ),
    OpDesc(
        canonical_id=7,
        name='sqrt',
        op_class='unary',
        ct_op='CT_OP_SQRT',
        ct_value=7,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('sqrt',),
        c_fn=None,
        tier1_class=None,
        notes="turing's Handler coarsens every elementary function to the catch-all Call; that is a lossy widening, not an equivalence.",
    ),
    OpDesc(
        canonical_id=8,
        name='exp',
        op_class='unary',
        ct_op='CT_OP_EXP',
        ct_value=8,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('exp',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=9,
        name='log',
        op_class='unary',
        ct_op='CT_OP_LOG',
        ct_value=9,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('log',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=10,
        name='neg',
        op_class='unary',
        ct_op='CT_OP_NEG',
        ct_value=10,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Neg',
        sympy=('neg',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=11,
        name='abs',
        op_class='unary',
        ct_op='CT_OP_ABS',
        ct_value=11,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Abs',
        sympy=('abs',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=12,
        name='round',
        op_class='unary',
        ct_op='CT_OP_ROUND',
        ct_value=12,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('round',),
        c_fn=None,
        tier1_class=None,
        notes="TRAP: turing's binary path normalizes reflected ops via `op[1:] if op.startswith(('i','r'))`. 'round' starts with 'r'. It is safe today only because unary ops are dispatched before that line -- any future binary op named with a leading i or r would silently mis-normalize.",
    ),
    OpDesc(
        canonical_id=13,
        name='trunc',
        op_class='unary',
        ct_op='CT_OP_TRUNC',
        ct_value=13,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler=None,
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes="COLLISION: this is C trunc() -- float round-toward-zero. It is NOT turing's Handler.Trunc, which is integer width truncation (see canonical op 'int_trunc'). A naive name-union merges these wrongly.",
    ),
    OpDesc(
        canonical_id=14,
        name='floor',
        op_class='unary',
        ct_op='CT_OP_FLOOR',
        ct_value=14,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('floor',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=15,
        name='ceil',
        op_class='unary',
        ct_op='CT_OP_CEIL',
        ct_value=15,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('ceiling',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=16,
        name='isfinite',
        op_class='unary',
        ct_op='CT_OP_ISFINITE',
        ct_value=16,
        arity=1,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler=None,
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Returns 1.0/0.0 in double storage; CTensor has no bool dtype (turing/docs/c_backend_status.md).',
    ),
    OpDesc(
        canonical_id=17,
        name='isnan',
        op_class='unary',
        ct_op='CT_OP_ISNAN',
        ct_value=17,
        arity=1,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler=None,
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=18,
        name='isinf',
        op_class='unary',
        ct_op='CT_OP_ISINF',
        ct_value=18,
        arity=1,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler=None,
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=19,
        name='logical_not',
        op_class='unary',
        ct_op='CT_OP_LOGICAL_NOT',
        ct_value=19,
        arity=1,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='NOT',
        handler='LNot',
        sympy=('not',),
        c_fn=None,
        tier1_class=None,
        notes="Logical (x == 0), distinct from bitwise 'invert'. nodus has ONE NOT opcode for both, so an emitter must choose ! vs ~ from operand dtype.",
    ),
    OpDesc(
        canonical_id=20,
        name='less',
        op_class='compare',
        ct_op='CT_OP_LT',
        ct_value=20,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Lt',
        sympy=('lt', 'strictlessthan'),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=21,
        name='less_equal',
        op_class='compare',
        ct_op='CT_OP_LE',
        ct_value=21,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Le',
        sympy=('le', 'lessthanorequal'),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=22,
        name='greater',
        op_class='compare',
        ct_op='CT_OP_GT',
        ct_value=22,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Gt',
        sympy=('gt', 'strictgreaterthan'),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=23,
        name='greater_equal',
        op_class='compare',
        ct_op='CT_OP_GE',
        ct_value=23,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Ge',
        sympy=('ge', 'greaterthanorequal'),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=24,
        name='equal',
        op_class='compare',
        ct_op='CT_OP_EQ',
        ct_value=24,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Eq',
        sympy=('eq', 'equality'),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=25,
        name='not_equal',
        op_class='compare',
        ct_op='CT_OP_NE',
        ct_value=25,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Ne',
        sympy=('ne', 'unequality'),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=26,
        name='maximum',
        op_class='binary',
        ct_op='CT_OP_MAXIMUM',
        ct_value=26,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='BINARY',
        handler=None,
        sympy=('max',),
        c_fn=None,
        tier1_class=None,
        notes='Binary arithmetic, not a predicate. It used to ride inside the old compare_value switch at case 6; the CTensorOp enum resolved that wart by giving it a first-class code.',
    ),
    OpDesc(
        canonical_id=27,
        name='minimum',
        op_class='binary',
        ct_op='CT_OP_MINIMUM',
        ct_value=27,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='BINARY',
        handler=None,
        sympy=('min',),
        c_fn=None,
        tier1_class=None,
        notes="Same history as 'maximum' (formerly compare_value case 7).",
    ),
    OpDesc(
        canonical_id=28,
        name='sign',
        op_class='unary',
        ct_op='CT_OP_SIGN',
        ct_value=40,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler=None,
        sympy=('sign',),
        c_fn=None,
        tier1_class=None,
        notes='CTensorOp returns -1.0, 0.0, or 1.0 in double storage.',
    ),
    OpDesc(
        canonical_id=29,
        name='invert',
        op_class='unary',
        ct_op='CT_OP_INVERT',
        ct_value=41,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='NOT',
        handler='Not',
        sympy=('invert',),
        c_fn=None,
        tier1_class=None,
        notes="Bitwise NOT (np.invert / torch.bitwise_not). Shares nodus's NOT opcode with 'logical_not'.",
    ),
    OpDesc(
        canonical_id=30,
        name='sin',
        op_class='unary',
        ct_op='CT_OP_SIN',
        ct_value=29,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('sin',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=31,
        name='cos',
        op_class='unary',
        ct_op='CT_OP_COS',
        ct_value=30,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('cos',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=32,
        name='tan',
        op_class='unary',
        ct_op='CT_OP_TAN',
        ct_value=31,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('tan',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=33,
        name='asin',
        op_class='unary',
        ct_op='CT_OP_ASIN',
        ct_value=32,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=34,
        name='acos',
        op_class='unary',
        ct_op='CT_OP_ACOS',
        ct_value=33,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=35,
        name='atan',
        op_class='unary',
        ct_op='CT_OP_ATAN',
        ct_value=34,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=36,
        name='sinh',
        op_class='unary',
        ct_op='CT_OP_SINH',
        ct_value=35,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=37,
        name='cosh',
        op_class='unary',
        ct_op='CT_OP_COSH',
        ct_value=36,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=38,
        name='tanh',
        op_class='unary',
        ct_op='CT_OP_TANH',
        ct_value=28,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=39,
        name='asinh',
        op_class='unary',
        ct_op='CT_OP_ASINH',
        ct_value=37,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=40,
        name='acosh',
        op_class='unary',
        ct_op='CT_OP_ACOSH',
        ct_value=38,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=41,
        name='atanh',
        op_class='unary',
        ct_op='CT_OP_ATANH',
        ct_value=39,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=42,
        name='bitand',
        op_class='binary',
        ct_op='CT_OP_BITAND',
        ct_value=42,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='AND',
        handler='And',
        sympy=('bitwise_and',),
        c_fn=None,
        tier1_class=None,
        notes="Shares nodus's AND opcode with 'logical_and'; operand dtype selects bitwise rather than truth semantics.",
    ),
    OpDesc(
        canonical_id=43,
        name='bitor',
        op_class='binary',
        ct_op='CT_OP_BITOR',
        ct_value=43,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='OR',
        handler='Or',
        sympy=('bitwise_or',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=44,
        name='bitxor',
        op_class='binary',
        ct_op='CT_OP_BITXOR',
        ct_value=44,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='XOR',
        handler='Xor',
        sympy=('bitwise_xor', 'xor'),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=45,
        name='shl',
        op_class='binary',
        ct_op='CT_OP_SHL',
        ct_value=45,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Shl',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='nodus has no top-level shift opcode, but GLSL/SPIR-V support <<; defining the BINARY sub-op space is what makes this lowerable at all.',
    ),
    OpDesc(
        canonical_id=46,
        name='shr',
        op_class='binary',
        ct_op='CT_OP_SHR',
        ct_value=46,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Shr',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes="See 'shl'.",
    ),
    OpDesc(
        canonical_id=47,
        name='logical_and',
        op_class='binary',
        ct_op='CT_OP_LOGICAL_AND',
        ct_value=47,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='AND',
        handler='LAnd',
        sympy=('and',),
        c_fn=None,
        tier1_class=None,
        notes='Operands are reduced to truth values and the result is stored as 1.0 or 0.0.',
    ),
    OpDesc(
        canonical_id=48,
        name='logical_or',
        op_class='binary',
        ct_op='CT_OP_LOGICAL_OR',
        ct_value=48,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='OR',
        handler='LOr',
        sympy=('or',),
        c_fn=None,
        tier1_class=None,
        notes='Operands are reduced to truth values and the result is stored as 1.0 or 0.0.',
    ),
    OpDesc(
        canonical_id=49,
        name='int_trunc',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='Trunc',
        sympy=('trunc',),
        c_fn=None,
        tier1_class=None,
        notes='COLLISION: Handler.Trunc is integer width truncation, NOT the float trunc() at CT_OP_TRUNC. Deliberately renamed so the two cannot merge.',
    ),
    OpDesc(
        canonical_id=50,
        name='zext',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='ZExt',
        sympy=('zext',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=51,
        name='sext',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='SExt',
        sympy=('sext',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=52,
        name='fptosi',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='FpToSi',
        sympy=('fptosi',),
        c_fn='cast_double_to_int_values',
        tier1_class=None,
        notes='C quantizes in place and returns double storage; CTensor has no integer dtype yet.',
    ),
    OpDesc(
        canonical_id=53,
        name='fptoui',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='FpToUi',
        sympy=('fptoui',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=54,
        name='sitofp',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='SiToFp',
        sympy=('sitofp',),
        c_fn='cast_double_to_float_values',
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=55,
        name='uitofp',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='UiToFp',
        sympy=('uitofp',),
        c_fn=None,
        tier1_class=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=56,
        name='matmul',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=False,
        reflectable=True,
        kernel_op=None,
        handler='Call',
        sympy=('matrix',),
        c_fn='matmul_double',
        tier1_class='contract',
        notes='Structured class CONTRACT: needs its own dispatch grid -- 2D invocation domain over (m, p) with an inner n-loop of multiply-accumulate, supplied by KernelIR.dispatch_grid. Never one elementwise instruction; that constraint stands. Still deliberately excluded from CTensorOp -- its dispatcher asserts every instruction writes one equally-shaped slot.',
    ),
    OpDesc(
        canonical_id=57,
        name='sum',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=('sum',),
        c_fn='sum_double',
        tier1_class='reduce',
        notes='Structured class REDUCE: cross-element combination along an axis; sub_op carries the combining operation (add). v1 SPIR-V realization is a single-invocation loop accumulating over the reduced extent; the cooperative form adds workgroup shared memory behind the already-reserved BARRIER opcode without changing the instruction.',
    ),
    OpDesc(
        canonical_id=58,
        name='mean',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='mean_dim',
        tier1_class='reduce',
        notes='Reduction: REDUCE(add) followed by an ordinary elementwise 1/n scale.',
    ),
    OpDesc(
        canonical_id=59,
        name='topk',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='topk_double',
        tier1_class='order',
        notes='Structured class ORDER: data-dependent ordering/selection. v1 realization contains the ordering entirely within one invocation (selection loop); cooperative forms are a later refinement behind the same class.',
    ),
    OpDesc(
        canonical_id=60,
        name='log_softmax',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='log_softmax_dim',
        tier1_class='reduce',
        notes='Composite expressible entirely with REDUCE plus the elementwise vocabulary: REDUCE(maximum), sub, exp, REDUCE(add), log, sub.',
    ),
    OpDesc(
        canonical_id=61,
        name='pad',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='pad_double_nd',
        tier1_class='remap',
        notes="Structured class REMAP: index-remapping copy with a fill scalar for out-of-source indices. Output allocation is the launcher's job -- shape is declared on the output value, never performed in-kernel.",
    ),
    OpDesc(
        canonical_id=62,
        name='stack',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='stack_double',
        tier1_class='remap',
        notes='REMAP with a leading-axis offset map.',
    ),
    OpDesc(
        canonical_id=63,
        name='cat',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='cat_double',
        tier1_class='remap',
        notes='REMAP with an axis offset map.',
    ),
    OpDesc(
        canonical_id=64,
        name='gather',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Load',
        sympy=('indexed',),
        c_fn='gather_pairs_2d',
        tier1_class='remap',
        notes="REMAP's indirect form: an index tensor operand supplies f(gid). Indirect addressing stays explicit in the instruction, not hidden in ADDR.",
    ),
    OpDesc(
        canonical_id=65,
        name='arange',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler=None,
        sympy=(),
        c_fn='create_arange',
        tier1_class='generate',
        notes='Structured class GENERATE: output is a pure function of the invocation index (start + gid*step). Creation allocates at the launcher, like every shape-declaring output.',
    ),
    OpDesc(
        canonical_id=66,
        name='br',
        op_class='control',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Br',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Unconditional edge to one successor block. Carries no value; the successor is named structurally, not computed.',
    ),
    OpDesc(
        canonical_id=67,
        name='condbr',
        op_class='control',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='CondBr',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Two-successor edge selected by a predicate operand. In a KPN this is a determinate demux: the predicate is a real operand, never a race on which input happens to have data.',
    ),
    OpDesc(
        canonical_id=68,
        name='indirectbr',
        op_class='control',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='IndirectBr',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Edge to one of several successors selected by a computed block address. The successor set is still enumerated structurally.',
    ),
    OpDesc(
        canonical_id=69,
        name='ret',
        op_class='control',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Ret',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes="Leave the closure, optionally publishing one result. The result becomes the closure's output rather than a value in the caller.",
    ),
    OpDesc(
        canonical_id=70,
        name='trap',
        op_class='control',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Trap',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Abort execution. Terminates a block like a return but publishes nothing and has no successor.',
    ),
    OpDesc(
        canonical_id=71,
        name='phi',
        op_class='control',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Phi',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Merge of one operand per predecessor edge. Variadic: arity is the predecessor count, which is a property of the block, not the op. Determinate because the predecessor is named, never selected by whichever operand arrives first.',
    ),
    OpDesc(
        canonical_id=72,
        name='select',
        op_class='control',
        ct_op=None,
        ct_value=None,
        arity=3,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='SELECT',
        handler='Select',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Value-level choice between two operands under a predicate. Unlike condbr this is not an edge: both operands are already values, so it is one Tier-0 instruction.',
    ),
    OpDesc(
        canonical_id=73,
        name='deploy',
        op_class='control',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Deploy',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Open a deployment scope: the region after this marker is scheduled as its own unit rather than inline with the enclosing program.',
    ),
    OpDesc(
        canonical_id=74,
        name='join',
        op_class='control',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Join',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Close the deployment scope opened by deploy, ordering the enclosing program after the deployed region completes.',
    ),
    OpDesc(
        canonical_id=75,
        name='alloca',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Alloca',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Reserve storage and yield a reference to it. The operand is the element count; the reference is an address in whatever space the owning memory backend provides.',
    ),
    OpDesc(
        canonical_id=76,
        name='store',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Store',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Write one value through a reference. Publishes no SSA result: the effect is the new memory state.',
    ),
    OpDesc(
        canonical_id=77,
        name='getelementptr',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='GetElementPtr',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Compute the address of an element within an aggregate from a base reference and an index. Addressing stays explicit in the instruction.',
    ),
    OpDesc(
        canonical_id=78,
        name='getattr',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='GetAttr',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Read one named field of a record, resolved against the record descriptor rather than by a runtime name lookup.',
    ),
    OpDesc(
        canonical_id=79,
        name='indexed',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Indexed',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Source-level subscript read, retained until record/index legalization rewrites it to getelementptr plus a load.',
    ),
    OpDesc(
        canonical_id=80,
        name='indexedstore',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=3,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='IndexedStore',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Source-level subscript write, the storing counterpart of indexed.',
    ),
    OpDesc(
        canonical_id=81,
        name='fill',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Fill',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Initialize a span to one repeated value. Zero-fill is the calloc case; the value is an operand so no separate zeroing op is needed.',
    ),
    OpDesc(
        canonical_id=82,
        name='strided_store_fill',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=3,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='StridedStoreFill',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Store one fixed-width scalar a counted number of times from a base address with an explicit signed byte stride. Iteration is visible in the instruction rather than hidden in a callback.',
    ),
    OpDesc(
        canonical_id=83,
        name='strided_memory_copy',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=3,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='StridedMemoryCopy',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Sequential fixed-width copies over versioned memory. Source and destination advance by the same explicit signed stride, so iteration order is observable when the regions overlap.',
    ),
    OpDesc(
        canonical_id=84,
        name='deepcopy',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Deepcopy',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes="Duplicate a value's whole owned storage graph. Not a flat byte copy: a field that is itself a reference names separate storage that a flat copy would leave shared between original and duplicate.",
    ),
    OpDesc(
        canonical_id=85,
        name='const',
        op_class='value',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Const',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Introduce a literal. Produces a value from nothing, so it is neither a computation nor addressed storage.',
    ),
    OpDesc(
        canonical_id=86,
        name='static_ref',
        op_class='value',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='StaticRef',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Introduce a reference to a statically known entity resolved at compile time, never a runtime address.',
    ),
    OpDesc(
        canonical_id=87,
        name='setattr',
        op_class='memory',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='void',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='SetAttr',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes="Write one named field of a record, resolved against the record descriptor. The storing half of the accessor pair: without it a field write is only a slot store and the field's name -- its meaning -- is lost in translation.",
    ),
    OpDesc(
        canonical_id=88,
        name='class_define',
        op_class='value',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='ClassDefine',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='State a class: its identity, instance-field layout and method bindings. The SSA module already holds this as a table; naming it here lets a definition cross a suite boundary as an operator instead of an out-of-band attachment.',
    ),
    OpDesc(
        canonical_id=89,
        name='field_define',
        op_class='value',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='FieldDefine',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes="State one instance field's addressable slot within a class layout.",
    ),
    OpDesc(
        canonical_id=90,
        name='method_define',
        op_class='value',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='MethodDefine',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='Bind a method name on a class to the function that implements it, so the class/function relationship survives translation.',
    ),
    OpDesc(
        canonical_id=91,
        name='function_define',
        op_class='value',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='FunctionDefine',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes='State a function or closure body as a definition rather than a call target, so an authored body -- and every constant inside it, such as a custom epsilon -- round-trips bit-exactly.',
    ),
    OpDesc(
        canonical_id=92,
        name='sigmoid',
        op_class='unary',
        ct_op='CT_OP_SIGMOID',
        ct_value=49,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        tier1_class=None,
        notes="Logistic activation as a primitive, not a composition. Assembled from comparisons, exp and a blend it recorded as one opaque op no backend had, so a model using it failed to lower. The stable branch lives once in C; abstract_nn's Sigmoid activation is the layer that wraps it.",
    ),
)

BY_NAME: dict[str, OpDesc] = {o.name: o for o in OPS}

BY_CANONICAL_ID: dict[int, OpDesc] = {o.canonical_id: o for o in OPS}

# sympy class name (lowercased, as keyed in transmogrifier.ssa_registry) -> canonical op.
BY_SYMPY: dict[str, OpDesc] = {s: o for o in OPS for s in o.sympy}

# turing CTensorOp ordinal -> canonical op.
BY_CT_VALUE: dict[int, OpDesc] = {
    o.ct_value: o for o in OPS if o.ct_value is not None
}

# turing Handler member -> canonical ops. A list, not a scalar: Handler.Call
# legitimately fans out across every elementary function.
BY_HANDLER: dict[str, list[OpDesc]] = {}
for _o in OPS:
    if _o.handler is not None:
        BY_HANDLER.setdefault(_o.handler, []).append(_o)
del _o


def resolve(op_string: str) -> tuple[OpDesc, bool] | None:
    """Resolve an AbstractTensor ``_apply_operator__`` op string.

    Returns ``(desc, reversed_operands)`` or None. Mirrors the i/r-prefix
    normalization in turing's c_backend, but only strips a prefix when doing so
    actually yields a known op -- so 'isnan', 'invert' and 'round' cannot be
    mangled into 'snan', 'nvert' and 'ound' the way blind stripping would.
    """
    direct = BY_NAME.get(op_string)
    if direct is not None:
        return direct, False
    if op_string[:1] in ('i', 'r'):
        base = BY_NAME.get(op_string[1:])
        if base is not None:
            return base, op_string[0] == 'r'
    return None


def lowerable_ops() -> tuple[OpDesc, ...]:
    """Ops expressible as a single KernelIR instruction."""
    return tuple(o for o in OPS if o.lowerable)


def holes(surface: str) -> tuple[OpDesc, ...]:
    """Ops with no implementation on ``surface``.

    This is the 'method union with holes marked' that operator_defs.py's
    mirrored_*_funcs built as data and nothing ever read.
    """
    if surface == 'c':
        return tuple(o for o in OPS if o.ct_op is None and o.c_fn is None)
    if surface == 'kernel_ir':
        return tuple(o for o in OPS if not o.lowerable)
    raise ValueError(f'unknown surface: {surface!r}')
