"""GENERATED FILE -- DO NOT EDIT.

Source:    ops/canonical_ops.json
Generator: ops/generate_canonical_ops.py
Rationale: research/15_the_missing_function_table.md
"""

from __future__ import annotations

from enum import IntEnum
from typing import NamedTuple


class CanonicalOp(IntEnum):
    """Append-only operation IDs shared by all lowering surfaces."""
    ADD = 0  # CT_OP_ADD
    SUB = 1  # CT_OP_SUB
    MUL = 2  # CT_OP_MUL
    TRUEDIV = 3  # CT_OP_DIV
    POW = 4  # CT_OP_POW
    MOD = 5  # CT_OP_MOD
    FLOORDIV = 6  # CT_OP_FLOORDIV
    SQRT = 7  # CT_OP_SQRT
    EXP = 8  # CT_OP_EXP
    LOG = 9  # CT_OP_LOG
    NEG = 10  # CT_OP_NEG
    ABS = 11  # CT_OP_ABS
    ROUND = 12  # CT_OP_ROUND
    TRUNC = 13  # CT_OP_TRUNC
    FLOOR = 14  # CT_OP_FLOOR
    CEIL = 15  # CT_OP_CEIL
    ISFINITE = 16  # CT_OP_ISFINITE
    ISNAN = 17  # CT_OP_ISNAN
    ISINF = 18  # CT_OP_ISINF
    LOGICAL_NOT = 19  # CT_OP_LOGICAL_NOT
    LESS = 20  # CT_OP_LT
    LESS_EQUAL = 21  # CT_OP_LE
    GREATER = 22  # CT_OP_GT
    GREATER_EQUAL = 23  # CT_OP_GE
    EQUAL = 24  # CT_OP_EQ
    NOT_EQUAL = 25  # CT_OP_NE
    MAXIMUM = 26  # CT_OP_MAXIMUM
    MINIMUM = 27  # CT_OP_MINIMUM
    SIGN = 28
    INVERT = 29
    SIN = 30
    COS = 31
    TAN = 32
    ASIN = 33
    ACOS = 34
    ATAN = 35
    SINH = 36
    COSH = 37
    TANH = 38
    ASINH = 39
    ACOSH = 40
    ATANH = 41
    BITAND = 42
    BITOR = 43
    BITXOR = 44
    SHL = 45
    SHR = 46
    LOGICAL_AND = 47
    LOGICAL_OR = 48
    INT_TRUNC = 49
    ZEXT = 50
    SEXT = 51
    FPTOSI = 52
    FPTOUI = 53
    SITOFP = 54
    UITOFP = 55
    MATMUL = 56
    SUM = 57
    MEAN = 58
    TOPK = 59
    LOG_SOFTMAX = 60
    PAD = 61
    STACK = 62
    CAT = 63
    GATHER = 64
    ARANGE = 65


class OpDesc(NamedTuple):
    name: str
    canonical_id: int
    op_class: str
    ct_op: str | None
    ct_value: int | None
    arity: int
    returns: str
    lowerable: bool
    reflectable: bool
    kernel_op: str | None
    handler: str | None
    sympy: tuple[str, ...]
    c_fn: str | None
    notes: str | None


OPS: tuple[OpDesc, ...] = (
    OpDesc(
        canonical_id=0,
        name='add',
        op_class='binary',
        ct_op='CT_OP_ADD',
        ct_value=0,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='BINARY',
        handler='Add',
        sympy=('add',),
        c_fn=None,
        notes='Commutative, so the reverse flag is a no-op.',
    ),
    OpDesc(
        canonical_id=1,
        name='sub',
        op_class='binary',
        ct_op='CT_OP_SUB',
        ct_value=1,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Sub',
        sympy=('sub',),
        c_fn=None,
        notes="numpy/torch _apply_operator__ return 'a - b' for BOTH 'sub' and 'rsub'; the C backend's explicit reverse flag is correct where those two are not.",
    ),
    OpDesc(
        canonical_id=2,
        name='mul',
        op_class='binary',
        ct_op='CT_OP_MUL',
        ct_value=2,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='BINARY',
        handler='Mul',
        sympy=('mul',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=3,
        name='truediv',
        op_class='binary',
        ct_op='CT_OP_DIV',
        ct_value=3,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Div',
        sympy=('div',),
        c_fn=None,
        notes='numpy guards via _safe_divide; C does not guard division by zero.',
    ),
    OpDesc(
        canonical_id=4,
        name='pow',
        op_class='binary',
        ct_op='CT_OP_POW',
        ct_value=4,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Pow',
        sympy=('pow',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=5,
        name='mod',
        op_class='binary',
        ct_op='CT_OP_MOD',
        ct_value=5,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Mod',
        sympy=('mod',),
        c_fn=None,
        notes='C now computes a - floor(a/b)*b (floored, numpy/torch-compatible) rather than fmod. An emitter must not lower this to GLSL mod() for signed operands without checking.',
    ),
    OpDesc(
        canonical_id=6,
        name='floordiv',
        op_class='binary',
        ct_op='CT_OP_FLOORDIV',
        ct_value=6,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler=None,
        sympy=(),
        c_fn=None,
        notes="turing's Handler has no floor-division member; it would coarsen to Div + floor.",
    ),
    OpDesc(
        canonical_id=7,
        name='sqrt',
        op_class='unary',
        ct_op='CT_OP_SQRT',
        ct_value=7,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('sqrt',),
        c_fn=None,
        notes="turing's Handler coarsens every elementary function to the catch-all Call; that is a lossy widening, not an equivalence.",
    ),
    OpDesc(
        canonical_id=8,
        name='exp',
        op_class='unary',
        ct_op='CT_OP_EXP',
        ct_value=8,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('exp',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=9,
        name='log',
        op_class='unary',
        ct_op='CT_OP_LOG',
        ct_value=9,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('log',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=10,
        name='neg',
        op_class='unary',
        ct_op='CT_OP_NEG',
        ct_value=10,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Neg',
        sympy=('neg',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=11,
        name='abs',
        op_class='unary',
        ct_op='CT_OP_ABS',
        ct_value=11,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Abs',
        sympy=('abs',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=12,
        name='round',
        op_class='unary',
        ct_op='CT_OP_ROUND',
        ct_value=12,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('round',),
        c_fn=None,
        notes="TRAP: turing's binary path normalizes reflected ops via `op[1:] if op.startswith(('i','r'))`. 'round' starts with 'r'. It is safe today only because unary ops are dispatched before that line -- any future binary op named with a leading i or r would silently mis-normalize.",
    ),
    OpDesc(
        canonical_id=13,
        name='trunc',
        op_class='unary',
        ct_op='CT_OP_TRUNC',
        ct_value=13,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler=None,
        sympy=(),
        c_fn=None,
        notes="COLLISION: this is C trunc() -- float round-toward-zero. It is NOT turing's Handler.Trunc, which is integer width truncation (see canonical op 'int_trunc'). A naive name-union merges these wrongly.",
    ),
    OpDesc(
        canonical_id=14,
        name='floor',
        op_class='unary',
        ct_op='CT_OP_FLOOR',
        ct_value=14,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('floor',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=15,
        name='ceil',
        op_class='unary',
        ct_op='CT_OP_CEIL',
        ct_value=15,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('ceiling',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=16,
        name='isfinite',
        op_class='unary',
        ct_op='CT_OP_ISFINITE',
        ct_value=16,
        arity=1,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler=None,
        sympy=(),
        c_fn=None,
        notes='Returns 1.0/0.0 in double storage; CTensor has no bool dtype (turing/docs/c_backend_status.md).',
    ),
    OpDesc(
        canonical_id=17,
        name='isnan',
        op_class='unary',
        ct_op='CT_OP_ISNAN',
        ct_value=17,
        arity=1,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler=None,
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=18,
        name='isinf',
        op_class='unary',
        ct_op='CT_OP_ISINF',
        ct_value=18,
        arity=1,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler=None,
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=19,
        name='logical_not',
        op_class='unary',
        ct_op='CT_OP_LOGICAL_NOT',
        ct_value=19,
        arity=1,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='NOT',
        handler='LNot',
        sympy=('not',),
        c_fn=None,
        notes="Logical (x == 0), distinct from bitwise 'invert'. nodus has ONE NOT opcode for both, so an emitter must choose ! vs ~ from operand dtype.",
    ),
    OpDesc(
        canonical_id=20,
        name='less',
        op_class='compare',
        ct_op='CT_OP_LT',
        ct_value=20,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Lt',
        sympy=('lt', 'strictlessthan'),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=21,
        name='less_equal',
        op_class='compare',
        ct_op='CT_OP_LE',
        ct_value=21,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Le',
        sympy=('le', 'lessthanorequal'),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=22,
        name='greater',
        op_class='compare',
        ct_op='CT_OP_GT',
        ct_value=22,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Gt',
        sympy=('gt', 'strictgreaterthan'),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=23,
        name='greater_equal',
        op_class='compare',
        ct_op='CT_OP_GE',
        ct_value=23,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Ge',
        sympy=('ge', 'greaterthanorequal'),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=24,
        name='equal',
        op_class='compare',
        ct_op='CT_OP_EQ',
        ct_value=24,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Eq',
        sympy=('eq', 'equality'),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=25,
        name='not_equal',
        op_class='compare',
        ct_op='CT_OP_NE',
        ct_value=25,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='CMP',
        handler='Ne',
        sympy=('ne', 'unequality'),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=26,
        name='maximum',
        op_class='binary',
        ct_op='CT_OP_MAXIMUM',
        ct_value=26,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='BINARY',
        handler=None,
        sympy=('max',),
        c_fn=None,
        notes='Binary arithmetic, not a predicate. It used to ride inside the old compare_value switch at case 6; the CTensorOp enum resolved that wart by giving it a first-class code.',
    ),
    OpDesc(
        canonical_id=27,
        name='minimum',
        op_class='binary',
        ct_op='CT_OP_MINIMUM',
        ct_value=27,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='BINARY',
        handler=None,
        sympy=('min',),
        c_fn=None,
        notes="Same history as 'maximum' (formerly compare_value case 7).",
    ),
    OpDesc(
        canonical_id=28,
        name='sign',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler=None,
        sympy=('sign',),
        c_fn=None,
        notes='HOLE: present on AbstractTensor, absent from CTensorOp.',
    ),
    OpDesc(
        canonical_id=29,
        name='invert',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='NOT',
        handler='Not',
        sympy=('invert',),
        c_fn=None,
        notes="Bitwise NOT (np.invert / torch.bitwise_not). HOLE in C. Shares nodus's NOT opcode with 'logical_not'.",
    ),
    OpDesc(
        canonical_id=30,
        name='sin',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('sin',),
        c_fn=None,
        notes='HOLE: CTensorOp has no trig at all, though numpy/torch _apply_operator__ handle the full set. This is the single largest per-surface gap in the table.',
    ),
    OpDesc(
        canonical_id=31,
        name='cos',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('cos',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=32,
        name='tan',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=('tan',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=33,
        name='asin',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=34,
        name='acos',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=35,
        name='atan',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=36,
        name='sinh',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=37,
        name='cosh',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=38,
        name='tanh',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=39,
        name='asinh',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=40,
        name='acosh',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=41,
        name='atanh',
        op_class='unary',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='UNARY',
        handler='Call',
        sympy=(),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=42,
        name='bitand',
        op_class='binary',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='AND',
        handler='And',
        sympy=('bitwise_and',),
        c_fn=None,
        notes="HOLE in C. Shares nodus's AND opcode with 'logical_and'.",
    ),
    OpDesc(
        canonical_id=43,
        name='bitor',
        op_class='binary',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='OR',
        handler='Or',
        sympy=('bitwise_or',),
        c_fn=None,
        notes='HOLE in C.',
    ),
    OpDesc(
        canonical_id=44,
        name='bitxor',
        op_class='binary',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='XOR',
        handler='Xor',
        sympy=('bitwise_xor', 'xor'),
        c_fn=None,
        notes='HOLE in C.',
    ),
    OpDesc(
        canonical_id=45,
        name='shl',
        op_class='binary',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Shl',
        sympy=(),
        c_fn=None,
        notes='nodus has no top-level shift opcode, but GLSL/SPIR-V support <<; defining the BINARY sub-op space is what makes this lowerable at all.',
    ),
    OpDesc(
        canonical_id=46,
        name='shr',
        op_class='binary',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=True,
        reflectable=True,
        kernel_op='BINARY',
        handler='Shr',
        sympy=(),
        c_fn=None,
        notes="See 'shl'.",
    ),
    OpDesc(
        canonical_id=47,
        name='logical_and',
        op_class='binary',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='AND',
        handler='LAnd',
        sympy=('and',),
        c_fn=None,
        notes='HOLE in C.',
    ),
    OpDesc(
        canonical_id=48,
        name='logical_or',
        op_class='binary',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='bool',
        lowerable=True,
        reflectable=False,
        kernel_op='OR',
        handler='LOr',
        sympy=('or',),
        c_fn=None,
        notes='HOLE in C.',
    ),
    OpDesc(
        canonical_id=49,
        name='int_trunc',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='Trunc',
        sympy=('trunc',),
        c_fn=None,
        notes='COLLISION: Handler.Trunc is integer width truncation, NOT the float trunc() at CT_OP_TRUNC. Deliberately renamed so the two cannot merge.',
    ),
    OpDesc(
        canonical_id=50,
        name='zext',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='ZExt',
        sympy=('zext',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=51,
        name='sext',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='SExt',
        sympy=('sext',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=52,
        name='fptosi',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='FpToSi',
        sympy=('fptosi',),
        c_fn='cast_double_to_int_values',
        notes='C quantizes in place and returns double storage; CTensor has no integer dtype yet.',
    ),
    OpDesc(
        canonical_id=53,
        name='fptoui',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='FpToUi',
        sympy=('fptoui',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=54,
        name='sitofp',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='SiToFp',
        sympy=('sitofp',),
        c_fn='cast_double_to_float_values',
        notes=None,
    ),
    OpDesc(
        canonical_id=55,
        name='uitofp',
        op_class='cast',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=True,
        reflectable=False,
        kernel_op='CAST',
        handler='UiToFp',
        sympy=('uitofp',),
        c_fn=None,
        notes=None,
    ),
    OpDesc(
        canonical_id=56,
        name='matmul',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=False,
        reflectable=True,
        kernel_op=None,
        handler='Call',
        sympy=('matrix',),
        c_fn='matmul_double',
        notes='Needs its own dispatch grid; not one elementwise instruction. Deliberately excluded from CTensorOp too -- their dispatcher asserts every instruction writes one equally-shaped slot.',
    ),
    OpDesc(
        canonical_id=57,
        name='sum',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=('sum',),
        c_fn='sum_double',
        notes='REDUCTION. KernelIR has no cross-invocation cooperation primitive at all (no workgroup-shared-memory opcode; SHUFFLE is intra-invocation), so this cannot be one kernel instruction.',
    ),
    OpDesc(
        canonical_id=58,
        name='mean',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='mean_dim',
        notes="Reduction; see 'sum'.",
    ),
    OpDesc(
        canonical_id=59,
        name='topk',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='topk_double',
        notes='Data-dependent ordering.',
    ),
    OpDesc(
        canonical_id=60,
        name='log_softmax',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='log_softmax_dim',
        notes='Composite with an embedded reduction.',
    ),
    OpDesc(
        canonical_id=61,
        name='pad',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=1,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='pad_double_nd',
        notes='Shape-changing; needs allocation.',
    ),
    OpDesc(
        canonical_id=62,
        name='stack',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='stack_double',
        notes='Variadic, shape-changing.',
    ),
    OpDesc(
        canonical_id=63,
        name='cat',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Call',
        sympy=(),
        c_fn='cat_double',
        notes='Variadic, shape-changing.',
    ),
    OpDesc(
        canonical_id=64,
        name='gather',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=2,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler='Load',
        sympy=('indexed',),
        c_fn='gather_pairs_2d',
        notes="Indirect addressing. nodus's own structured-spatial gather family in tensor_math (research/04) is deliberately outside this table.",
    ),
    OpDesc(
        canonical_id=65,
        name='arange',
        op_class='opaque',
        ct_op=None,
        ct_value=None,
        arity=0,
        returns='value',
        lowerable=False,
        reflectable=False,
        kernel_op=None,
        handler=None,
        sympy=(),
        c_fn='create_arange',
        notes="Creation op: allocates. Closer to KernelIR's VAR/CONST than to an arithmetic instruction.",
    ),
)

BY_NAME: dict[str, OpDesc] = {o.name: o for o in OPS}

BY_CANONICAL_ID: dict[int, OpDesc] = {o.canonical_id: o for o in OPS}

# sympy class name (lowercased, as keyed in transmogrifier.ssa_registry) -> canonical op.
BY_SYMPY: dict[str, OpDesc] = {s: o for o in OPS for s in o.sympy}

# turing CTensorOp ordinal -> canonical op.
BY_CT_VALUE: dict[int, OpDesc] = {
    o.ct_value: o for o in OPS if o.ct_value is not None
}

# turing Handler member -> canonical ops. A list, not a scalar: Handler.Call
# legitimately fans out across every elementary function.
BY_HANDLER: dict[str, list[OpDesc]] = {}
for _o in OPS:
    if _o.handler is not None:
        BY_HANDLER.setdefault(_o.handler, []).append(_o)
del _o


def resolve(op_string: str) -> tuple[OpDesc, bool] | None:
    """Resolve an AbstractTensor ``_apply_operator__`` op string.

    Returns ``(desc, reversed_operands)`` or None. Mirrors the i/r-prefix
    normalization in turing's c_backend, but only strips a prefix when doing so
    actually yields a known op -- so 'isnan', 'invert' and 'round' cannot be
    mangled into 'snan', 'nvert' and 'ound' the way blind stripping would.
    """
    direct = BY_NAME.get(op_string)
    if direct is not None:
        return direct, False
    if op_string[:1] in ('i', 'r'):
        base = BY_NAME.get(op_string[1:])
        if base is not None:
            return base, op_string[0] == 'r'
    return None


def lowerable_ops() -> tuple[OpDesc, ...]:
    """Ops expressible as a single KernelIR instruction."""
    return tuple(o for o in OPS if o.lowerable)


def holes(surface: str) -> tuple[OpDesc, ...]:
    """Ops with no implementation on ``surface``.

    This is the 'method union with holes marked' that operator_defs.py's
    mirrored_*_funcs built as data and nothing ever read.
    """
    if surface == 'c':
        return tuple(o for o in OPS if o.ct_op is None and o.c_fn is None)
    if surface == 'kernel_ir':
        return tuple(o for o in OPS if not o.lowerable)
    raise ValueError(f'unknown surface: {surface!r}')
